### ISSUE TITLE
Configuration of polynomial encodings

### ISSUE THREAD

**Issue by naure** [Inversed-Tech/eyelid#88] opened 2024-05-16 09:55 UTC
The polynomial encoding in https://github.com/Inversed-Tech/eyelid/pull/81 supports a single iris code size and a single polynomial configuration. This could made configurable, similarly to `PolyConf` or `YasheConf`.

See [this discussion](https://github.com/Inversed-Tech/eyelid/pull/82/files#r1599846550).

**Comment by teor2345** [comment] 2024-05-20 03:30
This seems like a duplicate of #84 and #90.

**Closed by teor2345** 2024-05-20 03:30 UTC
